### ISSUE TITLE
:sha512 and :sha384

### ISSUE THREAD

**Issue by ckoch-ncsa** [engineyard/hmac#4]
When signing a request with :sha512 and :sha384, it appears that the presence of a newline character in the signature can cause the signature validation to fail.

Is anyone else seeing this kind of problem?

I believe the use of Base64.strict_encode64 would eliminate the issue without impacting other signature digests.

**Comment by lanej** [comment]
@ckoch-ncsa can you give a sample body ? or just any body with a newline in it ?

**Comment by ckoch-ncsa** [comment]
@lanej 
It's not the body that causes an error it's the spec encode64 complies with; :encode64 includes newline chars at a fixed point (60 chars), per RFC2045 while strict_encode64 complies with RFC4648 where no line feeds are added. 
See: https://ruby-doc.org/stdlib-2.1.3/libdoc/base64/rdoc/Base64.html#method-i-encode64

This is not an issue with :sha256 signatures as they are less than 60 chars. 

It only appears in longer SHA hashes. 

Below is some example code illustrate the point. 

```ruby
def signature(key_secret, digest)
  Base64.encode64(
    OpenSSL::HMAC.digest(
      OpenSSL::Digest.new(digest.to_s), key_secret, "GET\n\n\n/some_path")).strip
end
encode64:
  signature("abcdef", :sha256) = "te0hL1veaPBq8vQEAyxSA6b0Okj/Qs7GsSUMwAXWuTU="

  signature("abcdef", :sha384) = "nZTR8vJdlDsej6DAjXOx1izpKjUloyMRKBhY053VwPwno3XtzL/j/7jHFKm8\nmjrO"

  signature("abcdef", :sha512) = "+hl/Mr4rI705JR/IzpR9iUinzrqeitVjKRur6azjxtdHcpCv7WtQGYiKmAwR\nc8qadHcGyaeZvm7MTgdKsw6e4w=="


def signature(key_secret, digest)
  Base64.strict_encode64(
    OpenSSL::HMAC.digest(
      OpenSSL::Digest.new(digest.to_s), key_secret, "GET\n\n\n/some_path")).strip
end
strict_encode64:
  signature("abcdef", :sha256) = "te0hL1veaPBq8vQEAyxSA6b0Okj/Qs7GsSUMwAXWuTU="

  signature("abcdef", :sha384) = "nZTR8vJdlDsej6DAjXOx1izpKjUloyMRKBhY053VwPwno3XtzL/j/7jHFKm8mjrO"

  signature("abcdef", :sha512) = "+hl/Mr4rI705JR/IzpR9iUinzrqeitVjKRur6azjxtdHcpCv7WtQGYiKmAwRc8qadHcGyaeZvm7MTgdKsw6e4w=="

```

**Comment by wyhaines** [comment]
I concur. I've dealt with the line break issue with encode64 before.  Switching to strict_encode64 should fix the problem.
